name: Build and push

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }} @ build-push-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - zephyr-esp32

    steps:
      - name: Some infos
        id: infos
        run: |
          echo github.run_id is ${{ github.run_id }}
          echo github.ref is ${{ github.ref }}
          echo github.head_ref is ${{ github.head_ref }}
          echo github.ref_name is ${{ github.ref_name }}
          echo github.sha is ${{ github.sha }}
          echo github.event_name is ${{ github.event_name }}
          echo github.repository_owner is ${{ github.repository_owner }}
          NAMESPACE=${{ github.repository || github.event.repository }}
          NAMESPACE_LC=${NAMESPACE,,}
          echo "namespace=${NAMESPACE_LC}" >> "$GITHUB_OUTPUT"
          echo namespace is ${NAMESPACE_LC}

      - name: Free disk space on runner
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get safe branch name and PR number
        id: tags
        run: |
          BRANCH_NAME=$(echo "${{ github.head_ref || github.ref_name }}" | sed 's,[/.],_,g')
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_NUMBER=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")
            echo "pr_number=${PR_NUMBER}" >> "$GITHUB_OUTPUT"
          else
            echo "pr_number=" >> "$GITHUB_OUTPUT"
          fi
          echo "safe_branch_name=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: ${{ matrix.target }}
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ steps.infos.outputs.namespace }}/${{ matrix.target }}:${{ github.sha }}
            ghcr.io/${{ steps.infos.outputs.namespace }}/${{ matrix.target }}:latest
